In [ ]:
#NumPy is a library (a toolbox of extra code someone else wrote) built specifically for fast, easy math on lots of numbers at once. 
It gives you a new type called an array, which looks similar to a list but behaves very differently when you do math on it#

In [1]:
import numpy as np

In [2]:
daily_demand = np.array([120, 135, 130, 140, 150, 145])
daily_demand

array([120, 135, 130, 140, 150, 145])

In [3]:
daily_demand / 1000

array([0.12 , 0.135, 0.13 , 0.14 , 0.15 , 0.145])

In [ ]:
#Exactly right — and notice what just happened: one line, no loop, and NumPy divided every single value by 1000 all at once#
#This is called vectorization — doing math on a whole array in a single operation, instead of looping through it one item at a time#

In [4]:
daily_demand + 10

array([130, 145, 140, 150, 160, 155])

In [5]:
daily_demand.mean()

np.float64(136.66666666666666)

In [6]:
daily_demand.max()

np.int64(150)

In [7]:
daily_demand.min()

np.int64(120)

In [8]:
daily_demand.sum()

np.int64(820)

In [ ]:
# Slicing means to grab a range of items using a colon: #

#This means "give me items from position 0 up to (but not including) position 3."#

In [9]:
daily_demand[0:3]

array([120, 135, 130])

In [10]:
daily_demand[3:]

array([140, 150, 145])