In [ ]:
#Filtering — picking out values that meet a condition#

In [1]:
import numpy as np

daily_demand = np.array([120, 135, 130, 140, 150, 145])

daily_demand > 135

array([False, False, False,  True,  True,  True])

In [2]:
daily_demand[daily_demand > 135]

array([140, 150, 145])

In [ ]:
#Combining conditions#

#With NumPy arrays, you use & (and) and | (or) instead — and each condition needs its own parentheses#

In [3]:
daily_demand[(daily_demand > 125) & (daily_demand < 145)]

array([135, 130, 140])

In [5]:
daily_demand[(daily_demand > 125) | (daily_demand < 145)]

array([120, 135, 130, 140, 150, 145])

In [ ]:
#generating a sequence of numbers automatically instead of typing them all by hand.#

In [6]:
hours = np.arange(24)
hours

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])