In [ ]:
# 2D arrays — rows and columns#
# real energy data usually looks like a table — rows and columns (e.g., each row a day, each column an hour).#
# NumPy handles this too, using what's called a 2D array#

In [1]:
import numpy as np

demand_table = np.array([
    [100, 120, 140, 110],
    [90, 130, 150, 100],
    [95, 125, 145, 105]
])
demand_table

array([[100, 120, 140, 110],
       [ 90, 130, 150, 100],
       [ 95, 125, 145, 105]])

In [2]:
demand_table.shape

(3, 4)

In [ ]:
# Accessing a specific value#

In [3]:
demand_table[0, 2]

np.int64(140)

In [ ]:
# Grabbing a whole row or column#

In [4]:
demand_table[0]

array([100, 120, 140, 110])

In [5]:
demand_table[:, 1]

array([120, 130, 125])

In [ ]:
# NB: That : means "all rows," and 1 picks just that one column#